[package]
name = "mimic-iv-clinical-database-demo-rust-crate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
csv = "1.3"
chrono = { version = "0.4", features = ["serde"] }
